### ISSUE TITLE
Change Text "Pick a date and a time"

### ISSUE THREAD

**Issue by dgiac85** [katemihalikova/ion-datetime-picker#10]
Hi! First of all my compliments for your awesome directive!
How can i change the text "Pick a date and a time"?
I Would to change it in Italian Language. 
I tried with $ionicPickerI18N but it does not work. I tried to add an attribute title in the directive ion-datetime-picker but still nothing! 
Any suggestion for this issue? Thanks!

**Comment by katemihalikova** [comment]
Hi Giacomo,
thank you very much!
You can translate it via `title` and `sub-title` attributes. They accept an expression so you need to use one of this:

```html
<ion-item ion-datetime-picker ng-model="val" title="'My title'" sub-title="'My sub title'">
    {{val}}
</ion-item>
```
or
```javascript
$scope.title = "My title";
$scope.subTitle = "My sub title";
```
```html
<ion-item ion-datetime-picker ng-model="val" title="title" sub-title="subTitle">
    {{val}}
</ion-item>
```

**Comment by dgiac85** [comment]
Oh Yes! It works! Thank you very much Kate! You are very kind!! 

Bye!
Giacomo

**Comment by hix41** [comment]
It solve my problem successfully.
THX!
