### ISSUE TITLE
Adding dates to today

### ISSUE THREAD

**Issue by ahsanzia341** [katemihalikova/ion-datetime-picker#106]
can I add +4 days to today? like e.g. only-valid="{'after': 'today', 'before':'today + 4' 'inclusive': true}"
Is there any way?

**Comment by katemihalikova** [comment]
No in this way, but you can do date math in your controller (using e.g. angular `date` filter, `Date` object methods, or `moment` library) and then use the value in the attr.

```javascript
$scope.todayPlus4 = "2017-04-14";
```
```mathematica
only-valid="{'after': 'today', 'before': todayPlus4, 'inclusive': true}"
```
