### ISSUE TITLE
Not getting value in controller

### ISSUE THREAD

**Issue by inceptivetech** [katemihalikova/ion-datetime-picker#108]
Hi,

I did the following code,

In HTML,

<div class="item" ion-datetime-picker monday-first seconds am-pm ng-model="clockinTime">
                    Date:
                    <strong>{{clockinTime | date: "yyyy-MM-dd h:mm:ss a"}}</strong>
                </div>

In .js file,

$scope.clockInTime = null;

I did not getting value in $scope.clockInTime after selecting date and time from datepicker. 
Also I refer your #81, but not getting solution
Please help me out.

Thanks

**Comment by inceptivetech** [comment]
"<class="item" ion-datetime-picker monday-first seconds am-pm ng-model="clockInTime">
                    <strong>{{clockInTime | date: "yyyy-MM-dd h:mm:ss a"}}</strong>
"

This is my html code

**Comment by katemihalikova** [comment]
Hi, see #14. Your have some nested scopes so you need to have a dot in your models.

**Comment by inceptivetech** [comment]
Thanks for quick reply.

I also refer #14 as well. 
Follow this http://stackoverflow.com/questions/17178943/does-my-ng-model-really-need-to-have-a-dot-to-avoid-child-scope-problems this link. 
But still issue is same. 
$scope.clockInTime getting null while submitting date & time to DB.

**Comment by katemihalikova** [comment]
`clockInTime` still doesn't have a dot in it.

**Comment by inceptivetech** [comment]
Yesssssss......!!!!!!!
Issue solve. 
Thank you so much....

I need one more help but not regarding this issue. Can you please help me out?

I select date and time from date picker. I add button on html for selecting current date & time. Value is update in controller but html not getting update. HTML showing me selected date & time from datepicker. not showing current date & time which is set from controller.
This is my following code from .js file

$scope.selectNow = function () {
        $scope.clockInTime = new Date().toISOString();
    }

HTML code is same as above.

**Comment by katemihalikova** [comment]
Same problem, `clockInTime` should have a dot.

**Comment by inceptivetech** [comment]
Yessssssss......!!!!!
Fix that...!!!!

Thank you very much....
Very happy....
Facing this issue from 3 days....
Thank you so much
