### ISSUE TITLE
Datetime output

### ISSUE THREAD

**Issue by varunsree** [katemihalikova/ion-datetime-picker#109]
Can i get datetime picker output as UNIX timestamp

**Comment by katemihalikova** [comment]
Use [`toISOString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).

**Comment by katemihalikova** [comment]
Use [`getTime`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime).
