### ISSUE TITLE
get only time from ion-datetime-picker

### ISSUE THREAD

**Issue by niyoma** [katemihalikova/ion-datetime-picker#122]
hi,
i am using ion-datetime-picker for time .
my code is :
<class="item" ion-datetime-picker time ng-model="storedetail.shopopeningtime">
    {{storedetail.shopopeningtime| date: "H:mm"}}
  </>  
i am getting following value in resonse
**Sun Dec 31 1899 11:00:00 GMT 0530 (India Standard Time)** 
I want only time field .
please help me with it

**Comment by katemihalikova** [comment]
Hi, please make a codepen/jsfiddle/whatever so I can see it if you want me to help you with Javascript/AngularJS basics.

**Comment by niyoma** [comment]
@katemihalikova thanx for your reply.
my problem got solved with getHours(),getMinutes() functions
