### ISSUE TITLE
"only-valid" is not working in ionic 3

### ISSUE THREAD

**Issue by sonicwong** [katemihalikova/ion-datetime-picker#123]
My code:
<ion-datetime picker [(ngModel)]="datetimeValue" only-valid="{'after': '2017-10-10'}" ></ion-datetime>

But all date still selectable.

**Comment by sonicwong** [comment]
Just found out the attribute should be:
`[onlyValid]="ov"`

Where **ov** is a variable defined in ts and it is a json object:
`ov = {'after': '2017-10-10'};`

**Comment by katemihalikova** [comment]
That's one solution, right. `[onlyValid]="{'after': '2017-10-10'}"` should work too.

**Comment by sonicwong** [comment]
It would be helpful if update the v3 readme:
https://github.com/katemihalikova/ion-datetime-picker/blob/ionic3/README.md

**Comment by mubasshir** [comment]
Kindly add same to Readme
