### ISSUE TITLE
how to get value in a controller ? 

### ISSUE THREAD

**Issue by 13122310958** [katemihalikova/ion-datetime-picker#14]
Hi ,

I can't get the value in a controller while using $scope.datetimeValue . 
Can you tell me how to do ? 

```
<label class="item item-icon-right" ion-datetime-picker ng-model="datetimeValue">
						<i class="icon ion-ios-grid-view-outline positive"></i>
						Departure Date/Time
						<strong>{{datetimeValue| date: "yyyy-MM-dd H:mm"}}</strong>
           			 </label>
```

Thank you very much !

**Comment by katemihalikova** [comment]
Hi, it seems like you are using nested scopes in your app. [This question](http://stackoverflow.com/questions/17178943/does-my-ng-model-really-need-to-have-a-dot-to-avoid-child-scope-problems) on StackOverflow can help you. Another solution would be to use `controllerAs` feature.

**Comment by 13122310958** [comment]
Yes , that's right , I have solved this problem !  Thank you !!
