### ISSUE TITLE
Save problem

### ISSUE THREAD

**Issue by messaoudmoha** [katemihalikova/ion-datetime-picker#15]
http://localhost:2480/function/Insta/createEvent/12:6/ddd/ddd/Thu%20Apr%2021%202016%2018:03:00%20GMT+0100%20(Paris,%20Madrid) 500 (Internal Server Error) 

 and all whta i want to have is : 2016-04-09 00:55:00
 how can i do it or fix it please?
 thank you

**Comment by katemihalikova** [comment]
Use `$scope.modelValue.toISOString()` or similar.

**Comment by messaoudmoha** [comment]
can not read the property .toISOString() it's alwys the same problem

**Comment by katemihalikova** [comment]
Seems like your problem lies in your app, not in this component.

```
$scope.modelValue = new Date();
// modifying with the picker
"http://Insta/createEvent/12:6/dddd/ddd/" + $scope.modelValue === "http://Insta/createEvent/12:6/dddd/ddd/Wed Apr 13 2016 10:34:00 GMT+0100 (Paris, Madrid)"
"http://Insta/createEvent/12:6/dddd/ddd/" + $scope.modelValue.toISOString() === "http://Insta/createEvent/12:6/dddd/ddd/2016-04-13T09:34:00.000Z"
```

Modify it to fit your needs. Sorry for the lack of more help, but this issue is not a place for learning you the basics of javascript.

**Comment by messaoudmoha** [comment]
POST http://Insta/createEvent/12:6/ddd/dddd/2016-04-08**T**09:56:41**.138Z **
 how can i take of .138Z and change T with a space thankyou for your help

**Comment by katemihalikova** [comment]
```javascript
$scope.modelValue.toISOString().replace("T", " ").replace(/\.[0-9]{3}Z$/, "");
```

**Comment by messaoudmoha** [comment]
Thank you very much
