### ISSUE TITLE
keep getting "Cannot GET /picker-popup.html?"

### ISSUE THREAD

**Issue by caotian** [katemihalikova/ion-datetime-picker#16]
Hey guys, thanks for the awesome project.
I try it by the instructions , but i keep getting this error, "Cannot GET /picker-popup.html?",
so why my project keep to fetch template /picker-popup.html while your demo not?

**Comment by katemihalikova** [comment]
Hi, just a sole gal here :-) 
It seems you are using files from `src` folder. In that case you have to change `templateUrl` property in `picker.js` file on line 23 to your actual location. It is preferred to use files from `release` folder which work out of the box on any setup.
