### ISSUE TITLE
Open the popup with with different current date information

### ISSUE THREAD

**Issue by okyne-design** [katemihalikova/ion-datetime-picker#17]
Hi,
First, I want to thank you for your plugin, it is very cool.
My problem: I want to open the datetime popup with the date, I have already set and not the current date and hour.

For example, my ng-model is 2016-04-09T15:27:47+02:00. When I open the popup, I still have the current date info selected.
Is there a way to set the correct date if the ng-model is contains a date ?
Thx

**Comment by katemihalikova** [comment]
Hi,
it should work the way you described. It seems that you are not using an instance of `Date` in `ng-model`, are you? This component accepts only these instances, strings and timestamps are ignored. Try converting your value to a `Date` instance.

**Comment by okyne-design** [comment]
Oh Perfect, thanx. Using `Date` solved the issue
