### ISSUE TITLE
Does not work together with ion-item or any other directive with isolated scope

### ISSUE THREAD

**Issue by firmanhidayat** [katemihalikova/ion-datetime-picker#18]
Error: [$compile:multidir] Multiple directives [ionDatetimePicker (module: ion-datetime-picker), ionItem] asking for new/isolated scope on: <ion-item ion-datetime-picker="" ng-model="datetimeValue" class="ng-pristine ng-untouched ng-valid">

**Comment by katemihalikova** [comment]
Definitely a bug, thanks for the catch.

**Comment by katemihalikova** [comment]
Workaround for now is to use these directives on different elements.

**Comment by huangfang2015** [comment]
transform ion-item to div.

**Comment by firmanhidayat** [comment]
yes. I try this 👍    

<ion-content class="padding">
    <ion-list>
    	<div class='item' ion-datetime-picker ng-model="dateValue2">
        {{dateValue2| date: "yyyy-mm-dd H:mm:ss"}}
    	</div>
  	</ion-list>
  </ion-content>

work well.

thank you

**Comment by jonathan-chin** [comment]
I'm getting the same error. maybe you can edit the readme to show a different example?

**Comment by katemihalikova** [comment]
Changed readme to accommodate that, thanks!

**Comment by exaland** [comment]
Please help me , i want store in scope variable the date and time i choose .

at this time i can store the present time with new Date();

pls help me

**Comment by katemihalikova** [comment]
Your problem has nothing to do with this issue. You should file your own one. But this problem was already discussed many times, use search in issues.

**Comment by katemihalikova** [comment]
As I don't see an easy fix for that and a workaround exists, let's call it wontfix for the current version. The next version will use `component()` syntax of angular 1.5, so this problem won't happen anymore.
