### ISSUE TITLE
Is it possible to assign a specific date to the popup?

### ISSUE THREAD

**Issue by finddoc** [katemihalikova/ion-datetime-picker#2]
It seems it always shows the current time when the picker popup, is it possible to assign it with a specific date? Thanks.

**Comment by katemihalikova** [comment]
Of course it is. Provided `ng-model` value is always respected.

```javascript
    $scope.datetimeValue = new Date(2015, 5, 10, 14, 55, 5);
```
```html
    <ion-item ion-datetime-picker ng-model="datetimeValue">
        {{datetimeValue| date: "yyyy-mm-dd H:mm:ss"}}
    </ion-item>
```
Both shown value and default picker value will be set to *2015-06-10 14:55:05*.

**Comment by WangShayne** [comment]
Hi Kate!I try doing that,but it's look does't work.
my code:
`$rootScope.search = {
            "query": {
                "areaId": "",
                "locationId": "",
                "startDate": new Date(),
                "endDate": new Date(),
                "startTime": new Date(9,0),
                "endTime": new Date(10,0),
                "equipment":{
                    "hasProjector":"",
                    "hasMic":"",
                    "hasBoard":""
                }
            }
        };`
html
`<span>{{search.query.startTime | date: "HH:mm"}}</span>`
After the loading, it's look like "00:00"
sorry my English is bad

**Comment by katemihalikova** [comment]
`Date` uses this syntax: `new Date(year, month, day, hour, minute, second)`. You need to use `new Date(0, 0, 0, 9, 0, 0)` for `9:00`.

**Comment by WangShayne** [comment]
thanks a lot!!
