### ISSUE TITLE
Not Working with IOS Simulator and iPhone

### ISSUE THREAD

**Issue by pateltejasmca** [katemihalikova/ion-datetime-picker#21]
Hi,

Thanks for developing a very useful plugin. It working fine with ionic server and even its working properly in my android but not working with ios.

I am too much confused how to solve this issues. 

In ios date picker model is appear but when i am clicking on Ok button date time value didnt fill in my input.

Kindly help me and thanks in advance.

Here is my code
`<input type="text" placeholder="e.g 25-12-2016 14:00" ion-datetime-picker id="interview_date_time" name="interview_date_time" ng-model="datetimeValue" readonly="readonly"  value="{{datetimeValue| date: 'yyyy-MM-dd H:mm'}}" required="required"  />`

**Comment by katemihalikova** [comment]
Hi Tejas,
this is not how it is supposed to be done. Use non-input element and style it instead. Furthermore, you are using interpolation in `value` attr, but its behaviour is undefined in angular.

**Comment by pateltejasmca** [comment]
Then how its working in Android ?

**Comment by katemihalikova** [comment]
Undefined behaviour means Sometimes works, sometimes not. Please use a proper angular way.

**Comment by pateltejasmca** [comment]
Thanks, Its working fine in my all device.

Thanks for your great support, I really appreciate your precious time for developing such a great plugin.

**Comment by katemihalikova** [comment]
Thanks, I'm glad you made it working 👍
