### ISSUE TITLE
Firefox 

### ISSUE THREAD

**Issue by Anzumana** [katemihalikova/ion-datetime-picker#22]
Input Elements are not being filled with the time /date that is being set by the datetime picker.
Increasing the Date and Time works its just not showing up in the input elements of the popup

**Comment by katemihalikova** [comment]
Please include a working snippet demonstrating the issue or provide steps to reproduce in demo.

**Comment by Anzumana** [comment]
If you open the demo from the readme in firefox
The input fields should show up empty but the binding is working as intended.
http://codepen.io/katemihalikova/full/dYvjzP/.
I opened a pull request that fixed it for me

**Comment by katemihalikova** [comment]
Thank you very much, I can reproduce it. The problem is one of Firefox flexbox quirks, I am going to fix it in next release.
