### ISSUE TITLE
Not Working For Text Field in Android

### ISSUE THREAD

**Issue by rahulg09** [katemihalikova/ion-datetime-picker#25]
Hello,

I am using ion-datetime-picker and it's nice. But It is not working for Text Box in my android mobile. 
Please help me to solve this issue. 

<input type="text"  placeholder="Date Time" ion-datetime-picker am-pm ng-model="visit.datetime" value="{{visit.datetime| date: 'dd-MM-yyyy h:mm:ss a'}}"  name="datetime"    required="required">

Thank You

**Comment by katemihalikova** [comment]
Hi Rahul,

it is not supposed to be working with an input field. You can't mix two different directives with ng-model. Please see #21 for a workaround.
