### ISSUE TITLE
Integration with Angular-Formly

### ISSUE THREAD

**Issue by chrisvor** [katemihalikova/ion-datetime-picker#26]
I'm trying to use your excellent component within a custom template in Angular-Formly but I can't do it. I'm not sure what I should call on the "onclick" event to show your component. Any suggestions?
(seasoned developer but very new to both Ionic and Angular-Formly :) )

Thanks !

**Comment by katemihalikova** [comment]
Hi Christos,
I'm not familiar with Angular-Formly at all, but this may help you:

Current version of the picker uses isolated scope to store its methods. You can access that scope if you have reference to the element with the `ion-datetime-picker `directive. From here, you can simply call `.showPopup()` method.

```javascript
angular.element(PICKER_ELEMENT).isolateScope().showPopup();
```

The directive also adds a click handler to the element itself so you can also use that with some kind of event bubbling.
