### ISSUE TITLE
Error just when navigating to the page that used ion-datetime-picker

### ISSUE THREAD

**Issue by rizadwia** [katemihalikova/ion-datetime-picker#30]
Hi, 
I always get this error when I navigate to the page that used this plugin:
`Error: [$compile:nonassign] Expression 'undefined' used with directive 'ionDatetimePicker' is non-assignable!`

I implement this in my html page:
`<div class="list">
	<a class="item">
		<h2>Arrived Time</h2>
		<p><div ion-datetime-picker ng-model="task.arrivalRealization">{{task.arrivalRealization | date: "yyyy-mm-dd H:mm:ss"}}</div></p>
	</a>
</div>`

Is there anything I need to change? Thanks.

**Comment by katemihalikova** [comment]
Could you please make up a demo? Codepen or fiddle or whatever. I will then look into it.

Please make sure that your model is defined.

**Comment by katemihalikova** [comment]
Duplicate of #32.
