### ISSUE TITLE
get some [$compile:nonassign] Expression 'undefined' Error

### ISSUE THREAD

**Issue by yaoyonstudio** [katemihalikova/ion-datetime-picker#32]
Hello! Thanks for the great work.

I use the plugin and get some error.
here's my code.

`<div ion-datetime-picker date ng-model="dateValue">
	Date:{{dateValue}}
</div>`

---------------------
![11](https://cloud.githubusercontent.com/assets/13121726/15533760/a7987a16-2298-11e6-8704-7a684615b9eb.jpg)

when I click the "Date:" ,It pops the picker box, but I also  get these error:

![22](https://cloud.githubusercontent.com/assets/13121726/15533873/f4ad5150-2298-11e6-91df-e398084dd322.jpg)

![ion-datetime-picker](https://cloud.githubusercontent.com/assets/13121726/15533740/959074cc-2298-11e6-850d-a33449730ba6.jpg)

need help , thank you very much.

**Comment by yaoyonstudio** [comment]
Just figure out , I need to set the "month-step","hour-step","minute-step".... manually .

Now It works fine. Here's my code .

`<div ion-datetime-picker date ng-model="dateValue" month-step="1" hour-step="1" minute-step="10" second-step="30">
	Date:{{dateValue | date: "yyyy-MM-dd"}}
</div>`

**Comment by katemihalikova** [comment]
Thanks for reporting that bug.

**Comment by katemihalikova** [comment]
This should be fixed in v0.2.1. Please let me know if it is working for you even when you don't set all attrs manually.

**Comment by yaoyonstudio** [comment]
Hi, @katemihalikova 

I update the js, and it works fine now.

Thanks for the great job.
