### ISSUE TITLE
Problem loading "picker-popup.html"

### ISSUE THREAD

**Issue by SamiAyed** [katemihalikova/ion-datetime-picker#33]
After installing the "0.2.1" version with bower install, i had a path error : "localhost:3000/lib/ion-datetime-picker/src/picker-popup.html not found", so i modified "ion-datetime-picker.min.js" file where i changed templateUrl from "lib/ion-datetime-picker/src/picker-popup.html" to "picker-popup.html" and i worked perfectly.
Please make sure to solve this issue.
`e.showPopup=function(){t.show({`**templateUrl:"picker-popup.html"**`,title:e.title||"Pick "+(e.dateEnabled?"a date":"")+(e.dateEnabled&&e.timeEnabled?" and ":"")+(e.timeEnabled?"a time":"")`

**Comment by katemihalikova** [comment]
Thanks for reporting that.
Seems like there were some problems when minifying files. This has been fixed with v0.2.2.
