### ISSUE TITLE
Time picker increment of 2 in mobile

### ISSUE THREAD

**Issue by kevinvavelin** [katemihalikova/ion-datetime-picker#34]
Hi,

I have an issue with the framework, when I run in ionic serve everything is good, but if I run it on phonegap I have the picker who increment my step twice.

Do you have any idea why I have this issue ?

Thanks in adance for your answer

**Comment by kevinvavelin** [comment]
Hi Kate,

I think the problem is related to Angular Material who fired the event twice. I run my app on iOS 9.3.3, Ionic 1.7.14, on web it's all good, but as soon as I am on mobile I have this problem.

I will test with remove angular-material to see if it's related and let you know about it

**Comment by songjiejoy** [comment]
add "$timeout(function() {……}, 50)“ to click event.
