### ISSUE TITLE
month jumps to july when current date is 31st of may

### ISSUE THREAD

**Issue by pbelouin** [katemihalikova/ion-datetime-picker#36]
the date in the field from which the picker is triggered is the 31st of may - when we open the clicker, and click on the arrow to go to the next month, we end up in july instead of june :) reproduced on 2 different codebase

**Comment by pbelouin** [comment]
ps thanks for your amazing work

**Comment by katemihalikova** [comment]
Thanks for reporting that, I will look into it soon.

**Comment by katemihalikova** [comment]
This has been fixed in 10308e9 and released as v0.2.3.
