### ISSUE TITLE
is there a way to get a callback when ok is pressed?

### ISSUE THREAD

**Issue by pliablepixels** [katemihalikova/ion-datetime-picker#4]
Hi, is there a way to get a callback when ok is pressed?

I need to call a custom function to update a view. I can do a watch for the ng-model, but its more expensive

**Comment by katemihalikova** [comment]
Hi, you can use `ng-change` in the same way as with any other input element.

```html
<ion-item ion-datetime-picker ng-model="datetimeValue" ng-change="datetimeChanged()">
```

**Comment by pliablepixels** [comment]
Ah yes of course. Thank you very much for this lovely library.

**Comment by katemihalikova** [comment]
Thanks for using it!
