### ISSUE TITLE
numeric keyboard doesn't show

### ISSUE THREAD

**Issue by przemkow** [katemihalikova/ion-datetime-picker#43]
According to my [pull request](https://github.com/katemihalikova/ion-datetime-picker/pull/42) on android  input types for _hours_, _minutes_ and _seconds_ doesn't show numerical keyboard. I tested this problem on android 5.0.1 with webview 37.0.0.0, android 4.4.4 with webview 32 and emulated android 6.0 with webview 44.0.0.0
Google says that android doesn't use pattern tag for providing keyboard so it would be nice to find other solution to show  proper keyboard on all platforms.

**Comment by katemihalikova** [comment]
Let's track this in #3.
