### ISSUE TITLE
Bug, Month text in month drop down list doesn't update

### ISSUE THREAD

**Issue by przemkow** [katemihalikova/ion-datetime-picker#44]
On android 5.0 Webview 37 (HUAWEI ALE-L21) i found a problem with refreshing month name in month drop down list. You can trigger this problem using steps bellow:
1. Open datetime-picker
2. Click on month drop down list
3. Chose month from list (for instance December) 
4. App will change its calendar view to chosen month(December) but in select label you still see previous month name
5. Chose different day in new month
6. Calendar will mark chosen day with blue background and update month name in select label to current one (December)

I also checked it on other device (Samsung GT-I9060I, android 4.4 with webview 32) and there everything works fine...

**Comment by przemkow** [comment]
@katemihalikova I was trying to fix that bug on all possible way but i couldn't find even a single working solution. On plugin side everything is done well, this bug is caused because of webview37(android5.0) in itself. Angular properly update value in `bind.month` after choosing a month, view is also updated properly but even with the right value in `ng-model` in `select` tag, webview doesn't change element to chosen one.
If someone has any other solution or walk-around which would fix it, I would be very grateful for letting me know :)

**Comment by katemihalikova** [comment]
Weird bug.. Maybe using Crosswalk would work around the problem?

**Comment by katemihalikova** [comment]
During fixing #20 I encountered some similar problem - the select was not updating properly sometimes. Could you please re-test the problem with picker version `0.3.1`? Thanks!

**Comment by przemkow** [comment]
hello! I'm so sorry that you needed to wait so long :) I've just checked it and it seems to work totally fine! Good job!

**Comment by katemihalikova** [comment]
I'm glad it gets fixed. Thanks for the info!
