### ISSUE TITLE
Using datetime-pick to submit as a text value in html forms

### ISSUE THREAD

**Issue by jeremiasgoh** [katemihalikova/ion-datetime-picker#45]
Hi, I want to show the text value of {{DOB| date: "yyyy-MM-dd"}} in my form after clicking the dates on the calendar, so when I press submit, my controller will be able to get the string format to sent to backend servlets for processing. However the current the value does not show in the UI after selecting the date on the calendar. Any idea how to solve it?  

*How can i display the value in form to submit?*

<<---register.html---->>
`<label class="item item-input " id="register-input19">
 <span class="input-label">DOB</span>
 <input type="tel"  ion-datetime-picker date ng-model="DOB"  value="{{DOB| date: 'yyyy MM-dd'}}"  >  </label> ` 

<<---controller.js---->>`.controller('registerCtrl', function($scope, $http, $state, $ionicPickerI18n) {

        $scope.DOB = new Date();
        $ionicPickerI18n.weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
        $ionicPickerI18n.months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
        $ionicPickerI18n.ok = "Select";
        $ionicPickerI18n.cancel = "Cancel";

**Comment by katemihalikova** [comment]
Hi Jeremias,

it is not supposed to be working with an input field. You can't mix two different directives that are using `ng-model`. Please see #21 for a workaround.

**Comment by jeremiasgoh** [comment]
can you help me with a working example? I cant find anything in the other
thread

**Comment by katemihalikova** [comment]
Yes, let's prepare a codepen/plunker/whatever demonstrating your issue and I'll take a look

**Comment by jeremiasgoh** [comment]
Not sure, how I can illustrate clearly with regards to the issue
specifically but most importantly, I want to submit the input from that
amazing date picker you made, (----->    value="{{DOB| date: 'yyyy MM-dd'}}
   <----  )     as a text, to my controller, to the backend for
processing.  Here is the codepen,

https://codepen.io/Zaperano/pen/xOqJYb

I appreciate your help as it for a school project. Thank you!

**Comment by jeremiasgoh** [comment]
Not sure, how I can illustrate clearly with regards to the issue
specifically but most importantly, I want to submit the input from that
amazing date picker you made, (----->    value="{{DOB| date: 'yyyy MM-dd'}}
   <----  )     as a text, to my controller, to the backend for
processing.  Here is the codepen,

https://codepen.io/Zaperano/pen/xOqJYb

I appreciate your help as it for a school project. Thank you!

**Comment by katemihalikova** [comment]
I sure hope you know that the task is easy and you should be supposed to find the answer yourself, right? :)

You can use `$scope.DOB.toISOString()` in your `$scope.register` method to get an ISO datetime string usable on server.

As i told you before, you just can't use two different directives using `ng-model` on one element.

```html
<div ion-datetime-picker date ng-model="DOB">Date of birth: {{DOB| date: 'yyyy MM-dd'}}</div>
```

**Comment by jeremiasgoh** [comment]
hi Kate,
Thank you :)
