### ISSUE TITLE
if this directive run in modal view, can't monitor click event

### ISSUE THREAD

**Issue by chgsh2008** [katemihalikova/ion-datetime-picker#47]
if this directive run in modal view, can't monitor click event.
it should be in $scope.on('modal.shown', function()
{
$element.on("click", $scope.showPopup);
});

**Comment by katemihalikova** [comment]
Please create a demo demonstrating your issue.

**Comment by chgsh2008** [comment]
In modal html code:
<ion-modal-view  ng-controller="ApproveTaskCtrl">
  <ion-header-bar class="bar bar-header bar-positive" hide-nav-bar="true">
    <div class="buttons">
      <button class="button button-icon icon ion-ios-arrow-back" ng-click="approveTaskModal.hide()"></button>
    </div>
    <h1 class="title">select date</h1>  
</ion-header-bar>
  <ion-content>
      <span class="input-label text-left">now date time:</span>
      <div class="text-left" ion-datetime-picker datetime isModal="true" ng-model="NextTask.planFinishTime">
        {{NextTask.planFinishTime | date: "yyyy-MM-dd HH:mm:ss"}}
      </div>
    </label>
  </ion-content>
</ion-modal-view>



in ion-datetime-picker directive code:

link: function($scope, $element, $attrs, ngModelCtrl) {
                $scope.dateEnabled = "date" in $attrs && $attrs.date !== "false";
                $scope.timeEnabled = "time" in $attrs && $attrs.time !== "false";
                if ($scope.dateEnabled === false && $scope.timeEnabled === false) {
                    $scope.dateEnabled = $scope.timeEnabled = true;
                }
                $scope.mondayFirst = "mondayFirst" in $attrs && $attrs.mondayFirst !== "false";
                $scope.secondsEnabled = $scope.timeEnabled && "seconds" in $attrs && $attrs.seconds !== "false";
                $scope.meridiemEnabled = $scope.timeEnabled && "amPm" in $attrs && $attrs.amPm !== "false";

                $scope.monthStep = +$scope.monthStep || 1;
                $scope.hourStep = +$scope.hourStep || 1;
                $scope.minuteStep = +$scope.minuteStep || 1;
                $scope.secondStep = +$scope.secondStep || 1;

                $scope.prepare();

                ngModelCtrl.$render = function() {
                    $scope.modelDate = ngModelCtrl.$viewValue;
                    $scope.processModel();
                };

                $scope.commit = function() {
                    $scope.modelDate = new Date($scope.year, $scope.month, $scope.day, $scope.hour, $scope.minute, $scope.second);
                    ngModelCtrl.$setViewValue($scope.modelDate);
                };

                var isModal = attr.isModal;
                if(isModal == true || isModal == 'true') {
                  $scope.$on('modal.shown', function() {
                    $element.on("click", $scope.showPopup);
                  });
                }else {
                  $element.on("click", $scope.showPopup);
                }

            }


need judge whether this view is modal view, and monitor the click event in modal.shown.

**Comment by katemihalikova** [comment]
Works fine, see [codepen](http://codepen.io/katemihalikova/pen/ZOvYxR?editors=1010). Do you have a different setup?

**Comment by chgsh2008** [comment]
Do you have update the source code in github?
No, I just fork and fix this issue in my branch, but I don't know how to mix to min.js.

**Comment by chgsh2008** [comment]
in [codepen](http://codepen.io/katemihalikova/pen/ZOvYxR?editors=1010), I can't show the modal, are you work with my modal.shown code or use your code?

**Comment by katemihalikova** [comment]
I have used your modal html, but haven't done any other change to the picker code.

It's working fine in Chrome on both PC and mobile. What's your environment?
