### ISSUE TITLE
Two time picker, start and stop, set minimal stop time based on start time

### ISSUE THREAD

**Issue by Alkasih** [katemihalikova/ion-datetime-picker#48]
Nice plugin, love it. 

I have a question. How to set minimal stop time based on the selected start time if I have two timepicker? Can you help me, please. 

Start Time: 12:30 
then Stop Time must be from 12:31

I use only-valid="{'after': '12:30'}", but it doesn't help.

**Comment by katemihalikova** [comment]
Hi, it is currently not possible to limit time. You can implement your own `ng-model` validator that does this instead.
