### ISSUE TITLE
Year not showed in Internet Explorer

### ISSUE THREAD

**Issue by agusmroldan** [katemihalikova/ion-datetime-picker#49]
Hello! First of all, I want to be grateful with all of you for this work and help, it's quite useful for developers. 

I'm using ion-datetime-picker and I don't have any problems in Firefox and Chrome, but when I use it IE10, I'm able to open the calendar but the year is not displayed. If I click inside the box the year appears but a little bit cut. 

I include a screen capture with the appearance.

![sample](https://cloud.githubusercontent.com/assets/20045694/16943216/d0c02920-4d9a-11e6-9fa1-d91e64225cf0.png)

Do you know how to fix this error? Thanks a lot!

**Comment by katemihalikova** [comment]
Hi, unfortunately IE10 browser is not supported. This plugin tries to be as compatible as it can, but IE10 support is far beyond its scope.
