### ISSUE TITLE
The ui doesnt update

### ISSUE THREAD

**Issue by Alkasih** [katemihalikova/ion-datetime-picker#50]
Everything works fine in browser, but when run it on Android device, I can see the value is changed in `chrome://inspect/#devices` but not the ui (the input in android device). 

Any idea, please?

**Comment by Alkasih** [comment]
http://stackoverflow.com/questions/38493067/the-model-is-updating-but-not-the-ui

**Comment by katemihalikova** [comment]
Hi,

You should include a codepen/plnkr or at least some of your code, without it I'm not able to come up with any solution.

Please see #25 and #21 if it helps you, I think you could have the same problem.

**Comment by Alkasih** [comment]
Yes, the problem is similar. I think we could close this. Thank you very much.
