### ISSUE TITLE
Editing Minute Input field not behaving as in demo - Very weird Behaviour

### ISSUE THREAD

**Issue by MayankLogiciel** [katemihalikova/ion-datetime-picker#51]
First of all, Thanks for this awesome plugin.

The issue i am facing is easily understandable as below. I have not tested this issue on iOS yet. But on android i am facing this issue each time and on different devices with different android versions. I am also not facing this issue on desktop browser when running app through 'ionic serve' command.

1. I opened time picker and tap on minute input field, My cursor is in last position.
![1](https://cloud.githubusercontent.com/assets/8719380/17025717/308ef660-4f2b-11e6-96c1-f62a74ea9728.png)

2. I typed number 7 as in below screenshot

![2](https://cloud.githubusercontent.com/assets/8719380/17025732/40dfe704-4f2b-11e6-82fb-623425bb4669.png)

3. Then i typed number 8 and suddenly before i can see '078' it changed to some garbage value as in below screenshot and stays as it is and after focus out it changed to '07'. It behaves similar if i try to type number below '60' and doesn't work at all as expected.

![3](https://cloud.githubusercontent.com/assets/8719380/17025762/6548fea0-4f2b-11e6-8df5-18dbfc7ee875.png)

I have tried your demo on multiple devices and also on ionic view app and demo works perfectly.
But It doesn't work on my android devices and tablet.

The one major and main thing that is different in my android build is webview.

I am neither using default 'webview' nor 'crosswalk'. Instead i am using' webview+' provided by [Cocoon.io](https://cocoon.io) and is only avaiable through Cloud Build and not as open source plugin.

What could be reason 'webview+' or some timing related issues in plugin code(less likely for me) or something else?

Can you pls provide your valuable feedback or solution for this issue?

**Comment by katemihalikova** [comment]
Hi Mayank,
thanks for your interest in the plugin!

Unfortunately I don't know what's going on here. You can try these:
- adding `console.log($scope.minute, $scope.bind.minute, typeof $scope.minute, typeof $scope.bind.minute);` after lines [140](https://github.com/katemihalikova/ion-datetime-picker/blob/master/src/picker.js#L140), [144](https://github.com/katemihalikova/ion-datetime-picker/blob/master/src/picker.js#L144), [169](https://github.com/katemihalikova/ion-datetime-picker/blob/master/src/picker.js#L169), [184](https://github.com/katemihalikova/ion-datetime-picker/blob/master/src/picker.js#L184) and posting all those logs including any line numbers back here. 
- adding `$timeout(function(){` and `}, 1000)` around line [281](https://github.com/katemihalikova/ion-datetime-picker/blob/master/src/picker.js#L281) and trying again

Unfortunately, as I have no access to webview+, you have to do the debugging yourself.

**Comment by MayankLogiciel** [comment]
I will try as you suggested.. But i am confused how to put these console.log statements in a minified plugin file i am including and theres no unminified version for the plugin file..

**Comment by katemihalikova** [comment]
Feel free to use the `src` folder files instead. Thanks!

**Comment by MayankLogiciel** [comment]
I debugged as suggested. Pls find comments along with logs. It still shows garbage value.

![err2](https://cloud.githubusercontent.com/assets/8719380/17050606/da3af6fa-4fc1-11e6-8fb3-431e0cc4d6a3.png)

**Comment by katemihalikova** [comment]
Thanks for your help! It seems that your webview sets the input as invalid and its model is set empty, although all other browsers don't do this and still provide the wrong value to be changed.

I'm not able to do anything with that, but I'm going to make the time input elements more simple in the next version to prevent some other issues, stay tuned!
