### ISSUE TITLE
Any way to set a calculated max date using between?

### ISSUE THREAD

**Issue by bfalzarano** [katemihalikova/ion-datetime-picker#52]
Hi,  

using between how can I set a calculated max date ($scope.maxDate calculated and set in the controller) for the final value?  'final': 'maxDate' or 'final': '{{maxDate}}' is not working.

e.g.
`<div class='item' ion-datetime-picker am-pm only-valid="{'between': {'initial': 'today', 'final': 'maxDate'}, 'inclusive': true}" title="'From Date/Time'" ng-model="event.fromDate">`

controller.js
 ```
//maxDate set to 180 days from today
  $scope.maxDate = new Date(new Date().setDate(new Date().getDate()+180));
```

**Comment by bfalzarano** [comment]
ok so this appears to work  : )

`<div class='item' ion-datetime-picker am-pm only-valid="{'between': {'initial': 'today', 'final': maxDate}, 'inclusive': true}" title="'From Date/Time'" ng-model="event.fromDate">
`

controller.js
```
//maxDate set to 180 days from today
  $scope.maxDate = new Date(new Date().setDate(new Date().getDate()+180));
```

**Comment by katemihalikova** [comment]
Hi,
sure, you make to use valid javascript/angular expression there, including the "variable reference". I'm glad you worked it out yourself :)
