### ISSUE TITLE
Locale issue when selecting only time

### ISSUE THREAD

**Issue by jason4zhu** [katemihalikova/ion-datetime-picker#58]
My project is built upon ionic, and the code in html is as follows:

```<button class="button button-small button-light" time ion-datetime-picker ng-model="s">
                    text:{{s}}
        </button>```

When I select a time via datetime-picker, it outputs "text:"1899-12-31T14:13:00.000Z"", which should be "2016-08-09T15:13.00.000Z". The date picker has the same problem. Could anyone help me out with this sort-of locale problem? Thanks.

**Comment by katemihalikova** [comment]
Hi Jason,
I've created a [codepen](http://codepen.io/katemihalikova/pen/LkXrGr) with your setup. As the model is always a `Date` object, you should not handle it as a string.

If you select `15:13` in picker, your model `s` is `Date` instance, which, when converted to string as in your example, outputs `"1899-12-31T14:13:00.000Z"` (your selected time in ISO8601 format). If you want the time in the local timezone, extract hours and minutes from it yourself or using `moment` library or similar.

```js
var hours = $scope.s.getHours();
var minutes = $scope.s.getMinutes();
// or
var time = moment($scope.s).format("H:mm");
```

**Comment by jason4zhu** [comment]
Great! Thanks it works :P. But one more thing I'm still confused. If `s` is `Date` instance standing for `15:13`, Why will it output `14:13` when printing to console?

**Comment by katemihalikova** [comment]
I don't know which browser are you using, but my Chrome does this in console:

```javascript
» new Date()
« Tue Aug 09 2016 16:06:02 GMT+0200
» new Date().toISOString()
« "2016-08-09T14:06:20.762Z"
```

The first output shows time in local timezone, the second in UTC (2 hours difference here in Central Europe).
