### ISSUE TITLE
Dynamically changing the localization

### ISSUE THREAD

**Issue by leostaric** [katemihalikova/ion-datetime-picker#63]
Hi, 
I am out of options on where to ask, and fairly new to Ionic.
When I use app.run() to set the localization data in my app.js, it works.
However, when I try the same thing in my controller, it never gets executed. 
How am I supposed to change the localization if my user changes his prefered language while using the application?

**Comment by katemihalikova** [comment]
Hi,
the localization factory works fine for me, although it's limited - it does not change locale data of already opened picker, but this should be no issue. When locale data are changed and new picker is opened, it should use the new data. See [codepen](http://codepen.io/katemihalikova/pen/YGGWow) to see it working in action.
