### ISSUE TITLE
Change title of popup

### ISSUE THREAD

**Issue by NoFootDancer** [katemihalikova/ion-datetime-picker#65]
Good day, i have a problem while trying to change the title of the datepicker,
it doesn't work for me i'm afraid, i use "title" or "date-title" as said but nothing changes.
Can someone show me the correct way of doing it?

I'll give you my example

< div class="date-pck item" ion-datetime-picker date data-title="qqq" ng-model="dateInitial">{{dateInitial| date: "yyyy-MM-dd"}}</ div>

And then i'll show the results

![date](https://cloud.githubusercontent.com/assets/15345906/18641800/07b7ce4a-7e53-11e6-80c9-e3691c9e550d.png)

See? The title hasn't changed, if there's something i did wrong please help me.

**Comment by katemihalikova** [comment]
Hi,
this attr gets an expression - `title="'qqq'"`.

**Comment by NoFootDancer** [comment]
Oh, thank you!
I forgot to use the single quotes ''

< div class="date-pck item" ion-datetime-picker date title=" 'qqq' " ng-model="dateInitial">{{dateInitial| date: "yyyy-MM-dd"}}</div >

That solved my problem, i'm so grateful, thanks! :)
