### ISSUE TITLE
how to disable the future dates  "help-wanted"

### ISSUE THREAD

**Issue by madhavanks26** [katemihalikova/ion-datetime-picker#66]
Hi ,

 i'm trying that only-valid attribute by 
a)passing the values directly in tag
b)by assigning to the a controller variable and used that variable in the attribute
kindly help me or share a fiddle to hide the future dates

Thanks 
Madhavan S

**Comment by katemihalikova** [comment]
Hi, you need to provide more info or your code at least. Ideally you can create a codepen/plnkr/jsbin/whatever to show what's not working for you.

**Comment by madhavanks26** [comment]
hi kate,
[http://codepen.io/katemihalikova/pen/dYvjzP](url)

In the above codepen, if possible could u add a example how to use "only-valid" functionality, it would be great

Thanks 
Madhavan S

**Comment by katemihalikova** [comment]
`only-valid="{before: 'today', inclusive: true}"` should do it.

**Comment by madhavanks26** [comment]
thanks kate
