### ISSUE TITLE
Not able to use ion-datetime-picker twice in single view

### ISSUE THREAD

**Issue by sushantsawant** [katemihalikova/ion-datetime-picker#69]
I am trying to take start and end time. Given below is sample html.  After submitting form, it is giving same value for both start and end time. Please advise.

<div class="item" ion-datetime-picker time am-pm ng-model="start_event_time">
					{{start_event_time| date: "h:mm a"}}
				</div>
<div class="item" ion-datetime-picker time am-pm ng-model="end_event_time">
					{{end_event_time | date: "h:mm a"}}
				</div>

**Comment by katemihalikova** [comment]
Hi,
I can't see any problem in your code. Please make a codepen or similar demonstrating your problem.
