### ISSUE TITLE
android phone keyboard covered ion-datetime-picker 

### ISSUE THREAD

**Issue by wudilab** [katemihalikova/ion-datetime-picker#79]
I use ion-datetime-picker  in my project. It works very well.

However, during testing I find ion-datetime-picker on android phone will be covered by android keyboard.  

I try to google but didn't find any good solution.

no sure how to fix or get around or config.

**Comment by katemihalikova** [comment]
Seems like the whole app is being covered by the keyboard but it can be noticed in picker only. You need to test with the particular phone, no other fix exists.

This is out of scope of this plugin.

**Comment by wudilab** [comment]
Hi Kate

    I find a solution to get around it. it is simple but tricky.

.platform-android.keyboard-open .ion-datetime-picker-popup .popup {
     position:inherit;
     top:10px;
    left:50%;
    margin-left:-125px;
}

now once keyboard is pop up whole dialog will move up to top:10px.

This is the best way to get around it.

Regards

**Comment by wudilab** [comment]
This is ionic long-term bugs causing this issue. I also reply to ionic bugs in github.

**Comment by bettysteger** [comment]
This was my solution:

```
body.keyboard-open .ion-datetime-picker-popup {
    align-items: flex-start;
    padding-top: 10px;
}
```
