### ISSUE TITLE
Large font makes Mo (Monday) and We (Wednesday) wrap

### ISSUE THREAD

**Issue by Simpler1** [katemihalikova/ion-datetime-picker#8]
On my Samsung S4 running Android 5.0.1, when I set my system font size to "Large", the calendar view wraps the text for Monday and Wednesday such that the "M" appears on one line and "o" appears on the next.

Could the overall width be increased slightly to avoid this odd result?

Thanks

**Comment by katemihalikova** [comment]
@Simpler1 Could you please help me with fixing this? I can't reproduce it on my device, even if font size is set to "Large" or "Extra Large", the font size in picker does not change.

**Comment by Simpler1** [comment]
I can't reproduce this any more, so something may have changed with a Samsung update.

Closing.
Thanks...

**Comment by katemihalikova** [comment]
Thank you very much for you assistance!
