### ISSUE TITLE
Day short name

### ISSUE THREAD

**Issue by yorki404** [katemihalikova/ion-datetime-picker#80]
Is there any way to display day short name or day name ???

**Comment by katemihalikova** [comment]
<img src="https://github.com/katemihalikova/ion-datetime-picker/raw/screenshots/date.png?raw=true" width="150" align="right">There already are week day abbreviations in calendar in picker, see screenshot on right.

Do you want to display the day name in your UI? Displaying date in your UI is up to you. You can use angular [`date` filter](https://docs.angularjs.org/api/ng/filter/date) and its `EEE`, `EEEE`, or `fullDate` tokens.

**Comment by yorki404** [comment]
Thank you so much. That worked
I didn't know the right date filter token.
