### ISSUE TITLE
Option to show only working days in calendar month popup ??

### ISSUE THREAD

**Issue by MayankLogiciel** [katemihalikova/ion-datetime-picker#82]
is it possible to disable all sundays & saturdays and some particular dates in a month calendar view? I read the documentation and didn't find any option to achieve this. 

Actually i want to show only working days(Monday-Friday) in a calendar month. Can you guide me  to do that in the awesome plugin you made 👍

**Comment by katemihalikova** [comment]
Current implementation of disabling particular dates is not powerful enough to achieve what you want.

As a workaround, you can hide Saturday and Sunday columns via css:

```sass
.ion-datetime-picker {
  .calendar {
    .col:nth-child(1), .col:nth-child(7) {
      display: none;
    }
  }
}
```

(or children numbered 6 and 7 if using `monday-first`).

Please note that it is not perfect solution as it is still possible to select a weekend date by changing time, month or year. You should add your own `ngModel` validator and show some error message in your UI then.

**Comment by MayankLogiciel** [comment]
Thanks kate for your quick response and css fix. That will help :)
