### ISSUE TITLE
only show minutes 00,15,30,45

### ISSUE THREAD

**Issue by Alkasih** [katemihalikova/ion-datetime-picker#84]
Hi, what do I need to do to make the minutes range are only  00, 15, 30, 45?

Many thanks in urgent

**Comment by katemihalikova** [comment]
Hi, you need to set `minute-step="15"`, set minutes of your model value to one of `00,15,30,45` and optionally normalize the model value in `ng-change` event or add your own `ng-model` validator.

**Comment by Alkasih** [comment]
I love you, marry me please!  hehe

**Comment by katemihalikova** [comment]
Your reaction is not appropriate, we are not friends. We are professionals, please avoid that behaviour in the future. I know that you are not a native English speaker, neither I am, but I believe this is not polite in your area too. I'm going to delete last two comments now.
