### ISSUE TITLE
wiredep issues

### ISSUE THREAD

**Issue by Steffan-Ennis** [katemihalikova/ion-datetime-picker#9]
Hey looks like the current bower.json isn't playing nice with wiredep using gulp as the task runner. 
I had a quick look and the main and dependencies are there so I'm not sure how to fix this one with overrides.

Could be a problem with my task here's the code anyways

gulp.task('wire-vendor', function() {
  gulp.src('./www/index.html')
  .pipe(wiredep())
  .pipe(gulp.dest('./www'));
});

gulp.task('wire-app', function() {
  var target = gulp.src('./www/index.html');
  var sources = gulp.src(['./www/js/**/*.js', './www/resources/**/*.css'], {read: false});
  return target.pipe(inject(sources, {relative: true})).pipe(gulp.dest('./www'));
});

gulp.task('wiredep', ['wire-vendor','wire-app']);

**Comment by katemihalikova** [comment]
Hi Steffan,
could you provide more details on the `isn't playing nice` part? It is working fine for me with this setup:

```javascript
gulp.task('bower', function() {
    return gulp.src('www/index.html')
        .pipe(wiredep.stream({devDependencies: true}))
        .pipe(gulp.dest('www/'));
});
```
