### ISSUE TITLE
Title of popup is not changed

### ISSUE THREAD

**Issue by arshad104** [katemihalikova/ion-datetime-picker#91]
Hi, 

I am using this datetime-picker and I want change the title of the popup. Can you please clearify how I can achieve this? following is my code snipt.

 `<input ion-datetime-picker date monday-first title="MyTitle" ng-model="datetimeValue" type="text">
        {{dateValue| date: "yyyy-MM-dd"}}
        </input>`

Thanks

**Comment by katemihalikova** [comment]
Hi, see #88.
