### ISSUE TITLE
ng-model not retaining new datetime

### ISSUE THREAD

**Issue by suranavarun** [katemihalikova/ion-datetime-picker#92]
Hi,

After selecting new date if i click on OK button in popup the new date is not retained in ng-model, it always has the initial value assigned to it.

For example,
<div class="label" ion-datetime-picker am-pm ng-model="enddatetimeValue">
                {{enddatetimeValue| date: "h:mm a ,dd MMM yy"}}
        </div>

 on init if i assign new Date() to enddatetimeValue and then if i change the date in date picker and in button click try to access enddatetimeValue it always shows the new Date() assigned initially.

Varun

**Comment by katemihalikova** [comment]
Hi Varun, the demo is working fine, it seems like a problem in your code.
